--- 
blank_issues_enabled: true
contact_links:
  -
    name: "Documentation"
    about: "Please read the documentation before opening a new issue"
    url: "https://github.com/Sv443-Network/SvCoreLib/wiki"
  -
    name: "Chat"
    about: "If you want to chat with the Sv443 Network community or need help, you can join the Discord server"
    url: "https://dc.sv443.net"
